spring:
  batch:
    job:
      name: purchaseConfirmedJob

    jdbc:
      initialize-schema: always

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create-drop

  datasource:
    url: jdbc:h2:~/test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MYSQL
    driverClassName: org.h2.Driver
    username: sa
    password:
    hikari:
      maximum-pool-size: 5
